// src/lib/components/EnvConfigDialog.svelte
<script lang="ts">
  import { Dialog } from "bits-ui";
  import {
    Plus,
    Trash2,
    Check,
    RotateCcw,
    Save,
    Database,
    Pen,
    Globe,
    Link,
  } from "lucide-svelte";
  import InputDialog from "./InputDialog.svelte";
  import { db } from "$lib/db/repositories";

  import { envStore } from "$lib/store/env-store.svelte";
  import { appStore } from "$lib/store/app-store.svelte";

  interface Props {
    open: boolean;
    onCancel: () => void;
  }

  let { open, onCancel }: Props = $props();

  let isEditingPackName = $state(false);
  let editedPackName = $state("");

  // New variable input
  let newKey = $state("");
  let newValue = $state("");

  // Check if there are unsaved changes
  let hasChanges = $derived.by(() => {
    return (
      JSON.stringify(envStore.currentEnvPack?.vars) !==
      JSON.stringify(envStore.originalEnvPackVars)
    );
  });

  function startEditingPackName() {
    if (!envStore.currentEnvPack) return;
    editedPackName = envStore.currentEnvPack.name;
    isEditingPackName = true;
  }

  async function savePackName() {
    if (!envStore.currentEnvPack || !editedPackName.trim()) return;
    await envStore.updateEnvPackName(
      envStore.currentEnvPack.id,
      editedPackName.trim()
    );
    isEditingPackName = false;
  }

  async function handleAddVar() {
    if (!newKey || !envStore.currentEnvPack) return;
    envStore.currentEnvPack.vars?.push({ key: newKey, value: newValue });
    newKey = "";
    newValue = "";
  }

  async function handleDeleteVar(idx: number) {
    if (!envStore.currentEnvPack) return;
    envStore.currentEnvPack.vars = envStore.currentEnvPack.vars?.filter(
      (_, i) => i !== idx
    );
  }

  async function saveChanges() {
    if (!envStore.currentEnvPack) return;
    await db.envPacks.updateVars(
      envStore.currentEnvPack.id,
      envStore.currentEnvPack.vars ?? []
    );
  }

  async function activatePack() {
    if (!envStore.currentEnvPack || !appStore.currentCollection) return;

    try {
      // First, save any changes to variables
      if (hasChanges) {
        await saveChanges();
      }

      // Update the collection's pack reference
      await db.collections.updatePack(
        appStore.currentCollection.id,
        envStore.currentEnvPack.id
      );

      await envStore.setCurrentEnvPack(envStore.currentEnvPack.id);
      onCancel();

      // Don't set dialog state directly, let parent component handle it
      // open = false; // <-- Удаляем эту строку
    } catch (error) {
      console.error("Error activating environment pack:", error);
    }
  }

  function cancel() {
    isEditingPackName = false;
    onCancel();
  }

  function changeSelectedPackId(id: number) {
    envStore.setCurrentEnvPack(id);
  }

  async function handleConfirmAddPack(name: string) {
    if (!name.trim()) return;
    await envStore.addEnvPack(name.trim());
  }
</script>

<Dialog.Root bind:open onOpenChange={(v) => !v && cancel()}>
  <Dialog.Portal>
    <Dialog.Overlay class="fixed inset-0 bg-black/50" />
    <Dialog.Content
      class="fixed p-0 bg-stone-800 text-white rounded-lg w-[800px] h-[600px] max-w-[95vw] max-h-[90vh] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 shadow-xl overflow-hidden flex flex-col"
    >
      <div class="bg-stone-700 px-4 py-2 border-b border-stone-600">
        <Dialog.Title
          class="text-lg font-semibold flex items-center justify-between h-8"
        >
          <span>Переменные окружения</span>
          <div class="space-x-2">
            {#if hasChanges}
              <button
                onclick={envStore.resetCurrentEnvPackVars}
                class="px-3 py-1.5 bg-stone-600 hover:bg-stone-500 rounded-md transition-colors text-sm inline-flex items-center space-x-1"
              >
                <RotateCcw size="0.9em" />
                <span>Reset</span>
              </button>
              <button
                onclick={saveChanges}
                class="px-3 py-1.5 bg-stone-600 hover:bg-stone-500 rounded-md transition-colors text-sm inline-flex items-center space-x-1"
              >
                <Save size="0.9em" />
                <span>Save</span>
              </button>
            {/if}
            {#if envStore.currentEnvPack?.id !== null}
              <button
                onclick={activatePack}
                class="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 rounded-md transition-colors text-sm inline-flex items-center space-x-1 {appStore
                  .currentCollection?.pack_id === envStore.currentEnvPack?.id
                  ? 'opacity-50 cursor-not-allowed'
                  : ''}"
                disabled={appStore.currentCollection?.pack_id ===
                  envStore.currentEnvPack?.id}
              >
                <Check size="0.9em" />
                <span
                  >{appStore.currentCollection?.pack_id ===
                  envStore.currentEnvPack?.id
                    ? "Применен"
                    : "Применить"}</span
                >
              </button>
            {/if}
          </div>
        </Dialog.Title>
      </div>

      <div class="flex flex-1 overflow-hidden">
        <!-- Left sidebar: Packs -->
        <div class="w-68 border-r border-stone-700 p-4 flex flex-col h-full">
          <div class="overflow-y-auto flex-1">
            <div class="space-y-1">
              {#each envStore.envPacks as pack (pack.id)}
                {#if pack.collection_id === null || pack.collection_id === appStore.currentCollection?.id}
                  <button
                    onclick={() => changeSelectedPackId(pack.id)}
                    class="w-full text-left p-2 rounded-md transition-colors flex justify-between items-center group {envStore
                      .currentEnvPack?.id === pack.id
                      ? 'bg-stone-600'
                      : 'hover:bg-stone-700'}"
                  >
                    <div class="flex items-center gap-2">
                      {#if pack.collection_id === null}
                        <Globe size="0.9em" class="text-sky-400" />
                      {:else}
                        <Link size="0.9em" class="text-amber-400" />
                      {/if}
                      <span class="truncate font-medium text-sm"
                        >{pack.name}</span
                      >
                    </div>
                    {#if appStore.currentCollection?.pack_id === pack.id}
                      <span
                        class="text-xs px-1.5 py-0.5 bg-blue-500 text-white rounded-sm"
                        >Active</span
                      >
                    {/if}
                  </button>
                {/if}
              {/each}
            </div>
          </div>

          <div class="mt-2">
            <InputDialog
              title="Добавить пак переменных"
              label="Название пака"
              placeholder="Введите название пака"
              buttonText="Добавить"
              onConfirm={handleConfirmAddPack}
            >
              <Dialog.Trigger
                class="flex w-full items-center justify-center space-x-1 p-2 bg-stone-700 hover:bg-stone-600 rounded-md transition-colors text-sm"
              >
                <Plus size="0.9em" />
                <span>Добавить пак</span>
              </Dialog.Trigger>
            </InputDialog>
          </div>
        </div>

        <!-- Right content: Variables Table -->
        <div class="flex-1 flex flex-col h-full">
          <div class="p-4 flex-1 overflow-hidden flex flex-col gap-4">
            <div class="flex justify-between items-center h-8">
              <h3 class="font-medium text-stone-300 flex gap-2 items-center">
                <Database size="1.1em" class="text-stone-400" />
                {#if envStore.envPacks.length > 0 && envStore.currentEnvPack}
                  {#if isEditingPackName}
                    <input
                      bind:value={editedPackName}
                      class="bg-stone-700 border border-stone-600 focus:border-stone-500 px-2 py-1 rounded outline-none text-sm"
                      placeholder="Pack name"
                      onkeydown={(e) => e.key === "Enter" && savePackName()}
                    />
                  {:else}
                    <span>{envStore.currentEnvPack?.name}</span>
                    <span class="text-xs text-stone-400 ml-1">
                      {#if envStore.currentEnvPack.collection_id === null}
                        (Global)
                      {:else}
                        (Linked to: {appStore.collections.find(
                          (c) => c.id === envStore.currentEnvPack?.collection_id
                        )?.name})
                      {/if}
                    </span>
                  {/if}
                {:else if envStore.envPacks.length === 0}
                  No environment packs
                {:else}
                  No Pack Selected
                {/if}
              </h3>

              {#if envStore.currentEnvPack}
                <div class="flex gap-2 items-center">
                  <button
                    title={envStore.currentEnvPack.collection_id === null
                      ? appStore.currentCollection
                        ? "Link to current collection"
                        : "Link to collection (select one first)"
                      : "Make Global"}
                    onclick={() =>
                      envStore.toggleEnvPackScope(envStore.currentEnvPack!.id)}
                    class="p-1 hover:bg-stone-600 rounded-md text-stone-400 hover:text-white {envStore
                      .currentEnvPack.collection_id === null &&
                    !appStore.currentCollection
                      ? 'opacity-50 cursor-not-allowed'
                      : ''}"
                    disabled={envStore.currentEnvPack.collection_id === null &&
                      !appStore.currentCollection}
                  >
                    {#if envStore.currentEnvPack.collection_id === null}
                      <Link size="0.9rem" />
                    {:else}
                      <Globe size="0.9rem" />
                    {/if}
                  </button>
                  {#if isEditingPackName}
                    <button
                      onclick={savePackName}
                      class="p-1 hover:bg-green-600 rounded-md text-green-400 hover:text-white"
                      title="Save name"
                    >
                      <Save size="1rem" />
                    </button>
                  {:else}
                    <button
                      onclick={startEditingPackName}
                      class="p-1 hover:bg-stone-600 rounded-md text-stone-400 hover:text-white"
                      title="Edit name"
                    >
                      <Pen size="1rem" />
                    </button>
                  {/if}
                  <button
                    onclick={(e) => {
                      e.stopPropagation();
                      envStore.deleteEnvPack(envStore.currentEnvPack!.id);
                    }}
                    class="p-1 hover:bg-red-600 rounded-md text-red-400 hover:text-white"
                    title="Delete pack"
                  >
                    <Trash2 size="1rem" />
                  </button>
                </div>
              {/if}
            </div>

            <!-- Table Header -->
            {#if envStore.currentEnvPack?.vars?.length || 0 > 0}
              <div
                class="grid grid-cols-[1fr_1fr_auto] gap-2 mb-2 text-xs font-medium text-stone-400 px-1"
              >
                <div>KEY</div>
                <div>VALUE</div>
                <div></div>
              </div>
            {/if}

            <!-- Variables Table -->
            <div class="overflow-y-auto flex-1 pr-1">
              {#if envStore.envPacks.length === 0}
                <div
                  class="flex flex-col items-center justify-center h-full text-center p-4"
                >
                  <p class="text-gray-500">
                    No environment collections have been created.
                  </p>
                </div>
              {:else if envStore.currentEnvPack && envStore.currentEnvPack.vars?.length === 0}
                <div
                  class="flex flex-col items-center justify-center h-full text-center p-4"
                >
                  <p class="text-gray-500">No variables defined</p>
                </div>
              {:else if envStore.currentEnvPack?.vars && envStore.currentEnvPack.vars.length > 0}
                <div class="space-y-1">
                  {#each envStore.currentEnvPack.vars as v, i}
                    <div
                      class="grid grid-cols-[1fr_1fr_auto] gap-2 bg-stone-700 rounded-md p-2 group"
                    >
                      <input
                        bind:value={v.key}
                        class="bg-stone-700 border border-stone-600 focus:border-stone-500 p-1.5 rounded outline-none"
                        placeholder="Key"
                      />
                      <input
                        bind:value={v.value}
                        class="bg-stone-700 border border-stone-600 focus:border-stone-500 p-1.5 rounded outline-none"
                        placeholder="Value"
                      />
                      <button
                        onclick={() => handleDeleteVar(i)}
                        class="p-1.5 hover:bg-stone-600 rounded-md flex items-center justify-center text-stone-400 hover:text-white"
                      >
                        <Trash2 size="0.9em" />
                      </button>
                    </div>
                  {/each}
                </div>
              {/if}
            </div>

            <!-- Add New Variable -->
            {#if envStore.currentEnvPack !== null}
              <div class="mt-3 grid grid-cols-[1fr_1fr_auto] gap-2">
                <input
                  bind:value={newKey}
                  placeholder="New key"
                  class="bg-stone-700 border border-stone-600 focus:border-stone-500 p-2 rounded outline-none text-sm"
                />
                <input
                  bind:value={newValue}
                  placeholder="New value"
                  class="bg-stone-700 border border-stone-600 focus:border-stone-500 p-2 rounded outline-none text-sm"
                />
                <button
                  onclick={handleAddVar}
                  class="bg-stone-600 hover:bg-stone-500 p-2 rounded-md transition-colors flex items-center justify-center"
                >
                  <Plus size="1.1em" />
                </button>
              </div>
            {/if}
          </div>
        </div>
      </div>
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>

// src/components/EnvConfigDialog.tsx
// Env pack editor (⌘E): pack list on the left, its variables on the right.
//
// Edits live in a draft buffer until Save — selecting a pack here only opens
// it for editing; "Применить" is what points the collection at it.
import {
  Check,
  Globe,
  Link,
  Pencil,
  Plus,
  RotateCcw,
  Save,
  Trash2,
} from "lucide-react";
import { useState } from "react";
import { useShallow } from "zustand/shallow";
import {
  currentCollection,
  editingPack,
  envDirty,
  useApp,
  usableEnvPacks,
} from "../lib/store";
import type { EnvVar } from "../lib/types";
import { Button, IconButton, Input, Overlay, cn } from "./ui";

export function EnvConfigDialog() {
  const open = useApp((s) => s.envConfigOpen);
  const setOpen = useApp((s) => s.setEnvConfigOpen);
  const packs = useApp(useShallow(usableEnvPacks));
  const pack = useApp(editingPack);
  const dirty = useApp(envDirty);
  const collection = useApp(currentCollection);
  const draftVars = useApp((s) => s.draftVars);
  const setDraftVars = useApp((s) => s.setDraftVars);
  const resetDraftVars = useApp((s) => s.resetDraftVars);
  const saveDraftVars = useApp((s) => s.saveDraftVars);
  const selectEditingPack = useApp((s) => s.selectEditingPack);
  const createEnvPack = useApp((s) => s.createEnvPack);
  const renameEnvPack = useApp((s) => s.renameEnvPack);
  const deleteEnvPack = useApp((s) => s.deleteEnvPack);
  const toggleEnvPackScope = useApp((s) => s.toggleEnvPackScope);
  const activateEnvPack = useApp((s) => s.activateEnvPack);
  const promptDialog = useApp((s) => s.promptDialog);
  const confirmDialog = useApp((s) => s.confirmDialog);

  const [newVar, setNewVar] = useState<EnvVar>({ key: "", value: "" });

  if (!open) return null;

  const applied = pack != null && collection?.pack_id === pack.id;
  const isGlobal = pack?.collection_id === null;

  const patchVar = (i: number, patch: Partial<EnvVar>) =>
    setDraftVars(draftVars.map((v, j) => (j === i ? { ...v, ...patch } : v)));

  const addVar = () => {
    if (!newVar.key.trim()) return;
    setDraftVars([...draftVars, { ...newVar, key: newVar.key.trim() }]);
    setNewVar({ key: "", value: "" });
  };

  const addPack = async () => {
    const name = await promptDialog({
      title: "Новый пак переменных",
      label: "Название пака",
      placeholder: "dev / stage / prod",
      confirmLabel: "Добавить",
    });
    if (name) await createEnvPack(name);
  };

  const rename = async () => {
    if (!pack) return;
    const name = await promptDialog({
      title: "Переименовать пак",
      label: "Название пака",
      initialValue: pack.name,
      confirmLabel: "Сохранить",
    });
    if (name) await renameEnvPack(pack.id, name);
  };

  const remove = async () => {
    if (!pack) return;
    const ok = await confirmDialog({
      title: "Удаление пака",
      message: `Пак "${pack.name}" и все его переменные будут удалены. Коллекции, использующие его, останутся без переменных.`,
      danger: true,
    });
    if (ok) await deleteEnvPack(pack.id);
  };

  return (
    <Overlay
      onClose={() => setOpen(false)}
      closeOnEsc
      className="items-center bg-black/60"
    >
      <div className="flex h-[36rem] max-h-[90vh] w-[50rem] max-w-[95vw] flex-col overflow-hidden rounded-lg border border-zinc-700 bg-zinc-900 shadow-2xl">
        {/* header */}
        <div className="flex h-12 shrink-0 items-center justify-between border-b border-zinc-800 px-4">
          <h2 className="text-[14px] font-semibold text-zinc-100">
            Переменные окружения
          </h2>
          <div className="flex items-center gap-2">
            {dirty && (
              <>
                <Button onClick={resetDraftVars} title="Вернуть сохранённые значения">
                  <RotateCcw size={12} /> Сбросить
                </Button>
                <Button onClick={() => void saveDraftVars()}>
                  <Save size={12} /> Сохранить
                </Button>
              </>
            )}
            {pack && (
              <Button
                variant="primary"
                disabled={applied && !dirty}
                title={
                  applied
                    ? "Этот пак уже применён к коллекции"
                    : `Применить "${pack.name}" к коллекции "${collection?.name}"`
                }
                onClick={() => void activateEnvPack(pack.id)}
              >
                <Check size={12} /> {applied ? "Применён" : "Применить"}
              </Button>
            )}
          </div>
        </div>

        <div className="flex min-h-0 flex-1">
          {/* packs */}
          <div className="flex w-56 shrink-0 flex-col border-r border-zinc-800 p-2">
            <div className="min-h-0 flex-1 space-y-0.5 overflow-y-auto">
              {packs.map((p) => (
                <button
                  key={p.id}
                  onClick={() => selectEditingPack(p.id)}
                  className={cn(
                    "flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-[12px]",
                    p.id === pack?.id
                      ? "bg-zinc-800 text-zinc-100"
                      : "text-zinc-300 hover:bg-zinc-800/60",
                  )}
                >
                  {p.collection_id === null ? (
                    <Globe size={12} className="shrink-0 text-sky-400" />
                  ) : (
                    <Link size={12} className="shrink-0 text-amber-400" />
                  )}
                  <span className="flex-1 truncate">{p.name}</span>
                  {collection?.pack_id === p.id && (
                    <span className="shrink-0 rounded bg-sky-600 px-1 py-px text-[9px] font-semibold text-white">
                      ACTIVE
                    </span>
                  )}
                </button>
              ))}
            </div>
            <Button onClick={addPack} className="mt-2 justify-center">
              <Plus size={12} /> Добавить пак
            </Button>
          </div>

          {/* variables */}
          <div className="flex min-w-0 flex-1 flex-col p-4">
            {!pack ? (
              <div className="flex flex-1 items-center justify-center text-[12px] text-zinc-600">
                {packs.length === 0
                  ? "Ещё нет ни одного пака переменных"
                  : "Пак не выбран"}
              </div>
            ) : (
              <>
                <div className="mb-3 flex h-7 items-center justify-between gap-2">
                  <div className="flex min-w-0 items-baseline gap-2">
                    <span className="truncate text-[13px] font-medium text-zinc-100">
                      {pack.name}
                    </span>
                    <span className="shrink-0 text-[11px] text-zinc-500">
                      {isGlobal
                        ? "(глобальный)"
                        : `(привязан к ${collection?.name ?? "коллекции"})`}
                    </span>
                  </div>
                  <div className="flex shrink-0 items-center gap-1">
                    <IconButton
                      title={
                        isGlobal
                          ? "Привязать к текущей коллекции"
                          : "Сделать глобальным"
                      }
                      disabled={isGlobal && !collection}
                      onClick={() => void toggleEnvPackScope(pack.id)}
                    >
                      {isGlobal ? <Link size={13} /> : <Globe size={13} />}
                    </IconButton>
                    <IconButton title="Переименовать" onClick={rename}>
                      <Pencil size={13} />
                    </IconButton>
                    <IconButton
                      title="Удалить пак"
                      onClick={remove}
                      className="hover:text-red-400"
                    >
                      <Trash2 size={13} />
                    </IconButton>
                  </div>
                </div>

                {draftVars.length > 0 && (
                  <div className="mb-1 grid grid-cols-[1fr_1fr_auto] gap-2 px-1 text-[10px] font-medium text-zinc-500">
                    <div>KEY</div>
                    <div>VALUE</div>
                    <div className="w-6" />
                  </div>
                )}

                <div className="min-h-0 flex-1 space-y-1 overflow-y-auto pr-1">
                  {draftVars.map((v, i) => (
                    <div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2">
                      <Input
                        value={v.key}
                        placeholder="key"
                        className="font-mono"
                        onChange={(e) => patchVar(i, { key: e.target.value })}
                      />
                      <Input
                        value={v.value}
                        placeholder="value"
                        className="font-mono"
                        onChange={(e) => patchVar(i, { value: e.target.value })}
                      />
                      <IconButton
                        title="Удалить переменную"
                        onClick={() =>
                          setDraftVars(draftVars.filter((_, j) => j !== i))
                        }
                        className="hover:text-red-400"
                      >
                        <Trash2 size={13} />
                      </IconButton>
                    </div>
                  ))}
                  {draftVars.length === 0 && (
                    <div className="flex h-full items-center justify-center text-[12px] text-zinc-600">
                      Переменных пока нет
                    </div>
                  )}
                </div>

                <form
                  onSubmit={(e) => {
                    e.preventDefault();
                    addVar();
                  }}
                  className="mt-3 grid grid-cols-[1fr_1fr_auto] gap-2 border-t border-zinc-800 pt-3"
                >
                  <Input
                    value={newVar.key}
                    placeholder="новый key"
                    className="font-mono"
                    onChange={(e) => setNewVar({ ...newVar, key: e.target.value })}
                  />
                  <Input
                    value={newVar.value}
                    placeholder="значение"
                    className="font-mono"
                    onChange={(e) => setNewVar({ ...newVar, value: e.target.value })}
                  />
                  <IconButton type="submit" title="Добавить переменную">
                    <Plus size={14} />
                  </IconButton>
                </form>
              </>
            )}
          </div>
        </div>
      </div>
    </Overlay>
  );
}
